/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2022-03-21 06:56:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<h1 align=\"left\">\r\n");
      out.write("\t<font color=\"red\">Rays Technologies</font>\r\n");
      out.write("</h1>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<div>\r\n");
      out.write("\t<img alt=\"\" src=\"D:/html/main.JPG\" height=\"300\" width=\"1000\">\r\n");
      out.write("\t<h5 align=\"\">\r\n");
      out.write("\t\tRays Technologies is premium Corporate Training and Placement company.\r\n");
      out.write("\t\tIt is providing training on cutting-edge technologies like AI, Machine\r\n");
      out.write("\t\tLearning, Spring, Angular, React, Java, Python, Automated Testing,\r\n");
      out.write("\t\tetc. After IIT and NIT, Rays is one of the leading institute in India\r\n");
      out.write("\t\tfrom where IT Engineers are getting highest packages in multinational\r\n");
      out.write("\t\tcompanies. <br> <br> Rays Technologies is an ISO 9001:2015\r\n");
      out.write("\t\tcertified Company. It was established in 2006 and is active in\r\n");
      out.write("\t\tmultiple cities in India. We started our company with âSUNRAYSâ brand\r\n");
      out.write("\t\tname that was later renamed RAYS Technologies in 2015. We primarily\r\n");
      out.write("\t\tdeal in Information Technology Services, Staffing Solutions, Corporate\r\n");
      out.write("\t\tTraining, and Career Consultancy. We aim at providing highly trained\r\n");
      out.write("\t\tcutting-edge IT professionals to the IT Industry. <br> <br>\r\n");
      out.write("\t\tWe provide training to Corporate Employees and Professionals in\r\n");
      out.write("\t\tend-to-end enterprise solutions. Our training contents are designed\r\n");
      out.write("\t\tand developed in accordance with the current industry standards and\r\n");
      out.write("\t\tfuture requirements. Our courses are highly valued in the corporate IT\r\n");
      out.write("\t\tworld. Our courses cover the most comprehensive portfolio of IT. <br>\r\n");
      out.write("\t\t<br> <br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>Disclaimer</h2>\r\n");
      out.write("\t\t<h5>\r\n");
      out.write("\t\t\tThe purpose of this Website is to help Computer Science students to\r\n");
      out.write("\t\t\tlearn and get practical examples of Java Programming Language and its\r\n");
      out.write("\t\t\tOpen Source frameworks. <br> <br> The above mentioned\r\n");
      out.write("\t\t\tcompanies in no way endorse, sponsor or associate us. The above logos\r\n");
      out.write("\t\t\tand trademarks are owned by their respective owners. We are not\r\n");
      out.write("\t\t\taffiliated with, and do not, in any way, claim to represent or own\r\n");
      out.write("\t\t\tany of the represented product trademarks or rights. This site is not\r\n");
      out.write("\t\t\tendorsed nor sponsored by the respective trademark owners in any way.\r\n");
      out.write("\t\t\t<br> <br> JAVA, ORACLE, SUN, SUN RAY Trademarks belong to\r\n");
      out.write("\t\t\tOracle America, Inc., merger of Sun Microsystems. No way we are\r\n");
      out.write("\t\t\tassociated or sponsored by them.\r\n");
      out.write("\t\t</h5>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
